### ISSUE TITLE
Red lights on Cetus.

### ISSUE THREAD

**Issue by Luniano** [BETAFPV/BETAFPV.github.io#4]
Red lights. I accidentally clicked on all 3 deleting data from Cetus. (In the configurator v3). And then I installed the firmware as in the video. Then the red lights lit up and after that nothing can fix it. I installed various firmwares, including litesilver frsky e.t.c. Drone came to life, but it never became stable. I also installed the very first firmware that I found here (Cetus_Brushed.bin). Where can I find additional firmware for FC, sensor and OSD.

**Comment by Luniano** [comment]
> Red lights. I accidentally clicked on all 3 deleting data from Cetus. (In the configurator v3). And then I installed the firmware as in the video. Then the red lights lit up and after that nothing can fix it. I installed various firmwares, including litesilver frsky e.t.c. Drone came to life, but it never became stable. I also installed the very first firmware that I found here (Cetus_Brushed.bin). Where can I find additional firmware for FC, sensor and OSD.



> Red lights. I accidentally clicked on all 3 deleting data from Cetus. (In the configurator v3). And then I installed the firmware as in the video. Then the red lights lit up and after that nothing can fix it. I installed various firmwares, including litesilver frsky e.t.c. Drone came to life, but it never became stable. I also installed the very first firmware that I found here (Cetus_Brushed.bin). Where can I find additional firmware for FC, sensor and OSD.

**Comment by wenzhicode** [comment]
Hi, Luniano.
Don't worry about it, you can work it out.
The firmware is [Here](https://github.com/BETAFPV/BETAFPV.github.io/releases/tag/v1), download three bin files(FC / Sensor / OSD); 
On the Flasher page, select the TAB option and download the corresponding firmware to the board, eg: selset Sensor tab,load FlowSensor_2021-05-12.bin, and click download;
Flash all three firmware are the same way, you need to hold down the key, power it up, and then select the corresponding serial port number in configure.

**Comment by Luniano** [comment]
Thank you so much! I managed to install the firmware. Just burned out in the grass. I'm waiting for a new one and will continue to use it.
