### ISSUE TITLE
Unhealthy sensor

### ISSUE THREAD

**Issue by kenken64** [BETAFPV/BETAFPV.github.io#5]
![image](https://user-images.githubusercontent.com/631205/125508372-41d49fa1-5cb1-4153-8079-add9842c5c88.png)

**Comment by kenken64** [comment]
It seems I cannot access the configurator

**Comment by wenzhicode** [comment]
Hi, kenken64.
Don't worry too much about the sensor UNHEALTH state, it is ok, just takes  a moment of stillness and it will get back to normal.. 

Your computer doesn't seem to have 100% display Scale, reset it to 100% Scale in Setting/Display.

**Comment by kenken64** [comment]
Change to 100% scale still cannot access configurator

![image](https://user-images.githubusercontent.com/631205/125647151-20373888-bbb5-48e7-a537-11296dfe952a.png)

**Comment by wenzhicode** [comment]
Are you connected to the correct serial port?

"cannot access configurator", could you be more specific?

**Comment by kenken64** [comment]
Yes I am connected to the serial port. Pls check the first screenshot connected

**Comment by kenken64** [comment]
The configurator tab is just not clickable. Other tabs is clickable

**Comment by kenken64** [comment]
Any updates? I want to reduce the Cetus drone throttle speed is too fast in sport mode
