### ISSUE TITLE
"Check error- server address error or json format error" after click update->check

### ISSUE THREAD

**Issue by RadekZareba** [BETAFPV/BETAFPV.github.io#8]
Hello, 
I have problem when I connect cetus pro to usb port and after that click update-> check. I would like try to change throttle in settings and update firmware but I always see the error. 
![image](https://user-images.githubusercontent.com/26517464/133884125-ddb0168e-dae0-400a-a826-a218bf5fcb82.png)

**Comment by TheKislota** [comment]
Same problem. and I can`t find guide for manual firmware upgrade

**Comment by HWT662988** [comment]
It can be updated with a new Configurator, which can be downloaded here:[BETAFPV_Configurator](https://github.com/BETAFPV/BETAFPV_Configurator/releases)
