### ISSUE TITLE
Cetus Pro flashing problem

### ISSUE THREAD

**Issue by tano68** [BETAFPV/BETAFPV.github.io#9]
Hi there, i encountered some problems with my cetus pro. First, after flashing the board and lost every single firmware (i've messed a lot), i've tried to load them back. mission accomplished for the main one (cetus pro 1.2.2), but where are the sensor and osd ones ?
Can't connect to Betafpv configurator either... ecxept for the firmware update procedure.
Please help me, i like that little thing.

**Comment by th0m4sek** [comment]
Did you find OSD firmware?
